window.LernovaAuth={
 client:null,
 init(){if(this.client)return this.client;const cfg=window.LERNOVA_CONFIG,key=cfg?.SUPABASE_PUBLISHABLE_KEY||cfg?.SUPABASE_ANON_KEY;if(!window.supabase||!cfg||!/^https:\/\/.+\.supabase\.co$/.test(cfg.SUPABASE_URL||'')||!key||key.includes('YOUR_'))return null;try{this.client=window.supabase.createClient(cfg.SUPABASE_URL,key);return this.client}catch(error){console.error('Lernova auth init failed',error);return null}},
 appBase(){const path=location.pathname,pageAt=path.indexOf('/pages/');return pageAt>=0?path.slice(0,pageAt+1):path.slice(0,path.lastIndexOf('/')+1)},
 nextPath(){const base=this.appBase(),candidate=new URLSearchParams(location.search).get('next')||'';if(candidate.startsWith(base)&&!candidate.includes('/pages/login.html')&&!candidate.includes('/pages/signup.html'))return candidate;return base+'index.html'},
 async session(){const c=this.client||this.init();return c?.auth.getSession()},
 async signUp(email,password,username){if(!this.client)throw new Error('Supabase يحتاج الإعداد أولًا.');return this.client.auth.signUp({email,password,options:{data:{username}}})},
 async signIn(email,password){if(!this.client)throw new Error('Supabase يحتاج الإعداد أولًا.');return this.client.auth.signInWithPassword({email,password})},
 async signInWithGoogle(){if(!this.client)throw new Error('Supabase يحتاج الإعداد أولًا.');return this.client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href,queryParams:{access_type:'offline',prompt:'consent'}}})},
 async signOut(){if(!this.client)return {error:new Error('Supabase يحتاج الإعداد أولًا.')};return this.client.auth.signOut()},
 async protectPage(){const path=location.pathname,lowerPath=path.toLowerCase(),authPage=lowerPath.endsWith('/pages/login.html')||lowerPath.endsWith('/pages/signup.html');document.body?.classList.add('auth-pending');try{const c=this.init();if(!c){if(!authPage){location.replace(this.appBase()+'pages/login.html?next='+encodeURIComponent(path+location.search+location.hash));return}}else{const {data,error}=await c.auth.getSession();if(error)console.warn('Lernova session check:',error.message);if(!data?.session&&!authPage){location.replace(this.appBase()+'pages/login.html?next='+encodeURIComponent(path+location.search+location.hash));return}if(data?.session&&authPage){location.replace(this.nextPath());return}}}catch(error){console.warn('Lernova auth check unavailable:',error.message);if(!authPage){location.replace(this.appBase()+'pages/login.html?next='+encodeURIComponent(path+location.search+location.hash));return}}document.body?.classList.remove('auth-pending')}
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>LernovaAuth.protectPage(),{once:true});else LernovaAuth.protectPage();
