document.addEventListener('DOMContentLoaded',()=>{
 const grid=document.getElementById('wordsGrid'),q=document.getElementById('searchInput'),sort=document.getElementById('sortSelect'),chapter=document.getElementById('chapterSelect');
 if(!grid)return;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let visible=40,filtered=[];
 function render(reset=true){if(reset)visible=40;let list=[...LERNOVA.search(q?.value)];if(chapter?.value)list=list.filter(w=>w.chapter===+chapter.value);switch(sort?.value){case'germanAsc':list.sort((a,b)=>a.german.localeCompare(b.german));break;case'germanDesc':list.sort((a,b)=>b.german.localeCompare(a.german));break;case'arabicAsc':list.sort((a,b)=>a.arabic.localeCompare(b.arabic));break;case'arabicDesc':list.sort((a,b)=>b.arabic.localeCompare(a.arabic));break;case'article':list.sort((a,b)=>a.article.localeCompare(b.article));break;case'type':list.sort((a,b)=>a.type.localeCompare(b.type));break;}filtered=list;grid.innerHTML=list.slice(0,visible).map(card).join('')||'<div class="empty">لا توجد كلمات مطابقة.</div>';if(visible<list.length)grid.insertAdjacentHTML('beforeend',`<button class="btn ghost load-more" type="button">عرض 40 كلمة أخرى (${list.length-visible} متبقية)</button>`);const count=document.getElementById('count');if(count)count.textContent=list.length;}
 function card(w){const key=LERNOVA.key(w),known=LernovaStore.known().includes(key);return `<article class="word-card ${known?'known':''}"><div class="word-top"><span class="article">${esc(w.article)}</span><h3>${esc(w.german)}</h3><button class="icon-btn speak" data-speak="${encodeURIComponent(w.german)}" aria-label="استمع إلى نطق المفرد">🔊</button></div><p class="arabic">${esc(w.arabic)}</p><div class="meta"><span>${esc(w.type||'—')}</span>${w.plural?`<span>Plural: ${esc(w.plural)} <button class="plural-speak" data-speak="${encodeURIComponent(w.plural)}" aria-label="استمع إلى نطق الجمع">🔊</button></span>`:''}<span>Kapitel ${w.chapter} · ${esc(w.category)}</span></div>${w.sentence?`<div class="sentence"><b>${esc(w.sentence)}</b><br><small>${esc(w.sentenceArabic||'')}</small></div>`:''}<div class="actions"><button class="btn primary known-btn" data-key="${encodeURIComponent(key)}">${known?'✓ محفوظ':'حفظ +5 XP'}</button><button class="btn ghost review-btn" data-key="${encodeURIComponent(key)}">مراجعة</button></div></article>`;}
 q?.addEventListener('input',render);sort?.addEventListener('change',render);chapter?.addEventListener('change',render);
 grid.addEventListener('click',e=>{if(e.target.closest('.load-more')){visible+=40;render(false);return;}const sp=e.target.closest('[data-speak]');if(sp)LERNOVA.speak(decodeURIComponent(sp.dataset.speak));const k=e.target.closest('.known-btn')?.dataset.key;if(k){LernovaStore.markKnown(decodeURIComponent(k));render(false);}const rev=e.target.closest('.review-btn')?.dataset.key;if(rev){LernovaStore.addReview(decodeURIComponent(rev));rev.disabled=true;rev.textContent='أُضيفت للمراجعة';}});
 LERNOVA.chapters().forEach(c=>chapter?.insertAdjacentHTML('beforeend',`<option value="${c.id}">Kapitel ${c.id} — ${esc(c.title)}</option>`));const chapterParam=new URLSearchParams(location.search).get('chapter');if(chapterParam&&chapter)chapter.value=chapterParam;render();window.addEventListener('lernova:synced',()=>render(false));
});
