// تدريبات قصيرة مستندة إلى ملخص القواعد الظاهر في صور Netzwerk neu A1، Kapitel 1–6.
window.LERNOVA_GRAMMAR_QUESTIONS = [
  {chapter:1,prompt:'Ich ___ Mohammed.',options:['bin','bist','ist'],answer:'bin',explanation:'مع ich نستخدم bin من الفعل sein.'},
  {chapter:1,prompt:'Wo ___ du?',options:['wohnst','wohne','wohnt'],answer:'wohnst',explanation:'مع du نضيف غالبًا ‎-st: du wohnst.'},
  {chapter:1,prompt:'Sie ___ aus Ägypten.',options:['kommt','kommen','komme'],answer:'kommt',explanation:'مع sie المفردة يأتي الفعل بصيغة ‎-t: sie kommt.'},
  {chapter:1,prompt:'Wie ___ Sie?',options:['heißen','heißt','heiße'],answer:'heißen',explanation:'Sie الرسمية تأخذ تصريف الجمع: Sie heißen.'},
  {chapter:1,prompt:'Wir ___ Deutsch.',options:['sprechen','spricht','spreche'],answer:'sprechen',explanation:'مع wir نستخدم المصدر: wir sprechen.'},
  {chapter:2,prompt:'Er ___ gern Fußball.',options:['spielt','spielen','spiele'],answer:'spielt',explanation:'مع er يأتي الفعل غالبًا بالنهاية ‎-t.'},
  {chapter:2,prompt:'___ du gern Musik?',options:['Hörst','Hört','Hören'],answer:'Hörst',explanation:'في سؤال نعم/لا يأتي الفعل أولًا، وتصريف du هو hörst.'},
  {chapter:2,prompt:'___ Sie Student?',options:['Sind','Ist','Bist'],answer:'Sind',explanation:'مع Sie الرسمية نستخدم sind.'},
  {chapter:2,prompt:'جمع der Tag هو ___.',options:['die Tage','die Tagen','die Tags'],answer:'die Tage',explanation:'الجمع الشائع لكلمة Tag هو Tage.'},
  {chapter:2,prompt:'Das ___ ein Hotel.',options:['ist','sind','bist'],answer:'ist',explanation:'Das مفرد، لذلك نقول: Das ist ein Hotel.'},
  {chapter:3,prompt:'Das ist ___ Hotel.',options:['ein','eine','einen'],answer:'ein',explanation:'Hotel محايد: ein Hotel.'},
  {chapter:3,prompt:'Das ist ___ Kirche.',options:['eine','ein','einen'],answer:'eine',explanation:'Kirche مؤنث: eine Kirche.'},
  {chapter:3,prompt:'Ich habe ___ Auto.',options:['kein','keine','keinen'],answer:'kein',explanation:'Auto محايد، ومع النفي نستخدم kein Auto.'},
  {chapter:3,prompt:'___ Sie bitte nach links!',options:['Gehen','Geht','Gehst'],answer:'Gehen',explanation:'صيغة الأمر الرسمية Sie: الفعل ثم Sie، مثل Gehen Sie!'},
  {chapter:3,prompt:'Die Wohnung ___ schön.',options:['ist','sind','hat'],answer:'ist',explanation:'مع الصفة نستخدم sein: Die Wohnung ist schön.'},
  {chapter:4,prompt:'Ich kaufe ___ Käse.',options:['den','das','dem'],answer:'den',explanation:'Käse مذكر، ومفعول الفعل kaufen يأخذ Akkusativ: den Käse.'},
  {chapter:4,prompt:'Ich esse ___ Banane.',options:['eine','ein','einen'],answer:'eine',explanation:'Banane مؤنث، وتبقى eine في Akkusativ.'},
  {chapter:4,prompt:'Was ___ du gern?',options:['isst','esse','essen'],answer:'isst',explanation:'تصريف essen مع du هو isst.'},
  {chapter:4,prompt:'Ich ___ gern Pizza.',options:['möchte','möchtest','möchten'],answer:'möchte',explanation:'مع ich نقول möchte.'},
  {chapter:4,prompt:'Morgens ___ Lina Müsli.',options:['isst','esse','essen'],answer:'isst',explanation:'Lina تعادل sie المفردة: sie isst.'},
  {chapter:5,prompt:'Der Kurs beginnt ___ 9 Uhr.',options:['um','am','von'],answer:'um',explanation:'نستخدم um مع الساعة المحددة: um 9 Uhr.'},
  {chapter:5,prompt:'___ Montag arbeite ich.',options:['Am','Um','Von'],answer:'Am',explanation:'نستخدم am مع أيام الأسبوع: am Montag.'},
  {chapter:5,prompt:'Das ist ___ Vater.',options:['mein','meine','meinen'],answer:'mein',explanation:'Vater مذكر في Nominativ: mein Vater.'},
  {chapter:5,prompt:'Ich ___ heute arbeiten.',options:['muss','musst','müssen'],answer:'muss',explanation:'مع ich نقول muss، ويأتي المصدر arbeiten في نهاية الجملة.'},
  {chapter:5,prompt:'Wir wollen heute ins Kino ___.',options:['gehen','geht','ging'],answer:'gehen',explanation:'بعد الفعل الناقص wollen يأتي الفعل الآخر مصدرًا في نهاية الجملة.'},
  {chapter:6,prompt:'___ ersten Mai habe ich frei.',options:['Am','Um','Im'],answer:'Am',explanation:'مع التاريخ نستخدم am: am ersten Mai.'},
  {chapter:6,prompt:'Ich lade dich ___.',options:['ein','lädt','einlade'],answer:'ein',explanation:'الفعل المنفصل einladen: الجزء ein يأتي في نهاية الجملة.'},
  {chapter:6,prompt:'Er trifft ___ am Freitag.',options:['mich','mir','ich'],answer:'mich',explanation:'الفعل treffen يأخذ Akkusativ: mich.'},
  {chapter:6,prompt:'Das Geschenk ist ___ den Vater.',options:['für','für dem','von'],answer:'für',explanation:'حرف الجر für يأخذ Akkusativ؛ نقول für den Vater.'},
  {chapter:6,prompt:'Gestern ___ ich keine Zeit.',options:['hatte','war','habe'],answer:'hatte',explanation:'الماضي البسيط من haben مع ich هو hatte.'},
  {chapter:7,prompt:'Ich ___ heute länger arbeiten.',options:['kann','kannst','können'],answer:'kann',explanation:'مع ich نستخدم kann، ويأتي المصدر arbeiten في نهاية الجملة.'},
  {chapter:7,prompt:'Morgen ___ wir früh aufstehen.',options:['müssen','muss','musst'],answer:'müssen',explanation:'مع wir نستخدم müssen، ويأتي المصدر في نهاية الجملة.'},
  {chapter:7,prompt:'Du ___ am Samstag Fußball spielen.',options:['willst','will','wollen'],answer:'willst',explanation:'تصريف wollen مع du هو willst.'},
  {chapter:7,prompt:'Er möchte Deutsch ___.',options:['lernen','lernt','lerne'],answer:'lernen',explanation:'بعد möchte يأتي الفعل الآخر مصدرًا في نهاية الجملة.'},
  {chapter:7,prompt:'___ Sie mir bitte helfen?',options:['Können','Kannst','Könnt'],answer:'Können',explanation:'السؤال الرسمي يبدأ بالفعل: Können Sie …?'} ,
  {chapter:8,prompt:'Der Film ___ um acht Uhr an.',options:['fängt','fangen','fange'],answer:'fängt',explanation:'الفعل anfangen منفصل، ومع er يأتي الفعل fängt في المركز الثاني وan في النهاية.'},
  {chapter:8,prompt:'Ich ___ um sieben Uhr ___.',options:['stehe … auf','aufstehe … —','steht … auf'],answer:'stehe … auf',explanation:'في الجملة الرئيسية تنفصل auf عن الفعل stehen وتأتي في النهاية.'},
  {chapter:8,prompt:'Wir ___ dich am Bahnhof ___.',options:['holen … ab','abholen … —','holt … ab'],answer:'holen … ab',explanation:'الفعل abholen ينفصل: holen … ab.'},
  {chapter:8,prompt:'Rufst du mich heute ___?',options:['an','auf','ein'],answer:'an',explanation:'الفعل anrufen ينفصل وتأتي an في آخر السؤال.'},
  {chapter:8,prompt:'Nach der Pause ___ wir ___.',options:['machen … weiter','weiter … machen','macht … weiter'],answer:'machen … weiter',explanation:'الفعل weitermachen ينفصل في الجملة الرئيسية.'},
  {chapter:9,prompt:'Heute ___ ich meine Mutter.',options:['besuche','besuchen','besucht'],answer:'besuche',explanation:'الفعل المصرف يبقى في المركز الثاني بعد ظرف الوقت.'},
  {chapter:9,prompt:'Am Abend ___ wir einen Film.',options:['sehen','sieht','sehe'],answer:'sehen',explanation:'بعد Am Abend يأتي الفعل المصرف في المركز الثاني؛ مع wir نقول sehen.'},
  {chapter:9,prompt:'Am Montag ___ du um neun Uhr.',options:['arbeitest','arbeite','arbeitet'],answer:'arbeitest',explanation:'مع du نضيف غالبًا ‎-st إلى الفعل.'},
  {chapter:9,prompt:'Morgen ___ der Zug um sechs Uhr.',options:['kommt','komme','kommen'],answer:'kommt',explanation:'مع der Zug المفرد نستخدم kommt.'},
  {chapter:9,prompt:'Danach ___ ich nach Hause.',options:['gehe','geht','gehen'],answer:'gehe',explanation:'بعد Danach يأتي الفعل في المركز الثاني، ومع ich نقول gehe.'},
  {chapter:10,prompt:'Gestern ___ ich Deutsch ___.',options:['habe … gelernt','bin … gelernt','hat … lernen'],answer:'habe … gelernt',explanation:'lernen يأخذ haben في Perfekt، وPartizip II في نهاية الجملة.'},
  {chapter:10,prompt:'Wir ___ nach Berlin ___.',options:['sind … gefahren','haben … gefahren','sind … fahren'],answer:'sind … gefahren',explanation:'fahren للتنقل يأخذ sein في Perfekt.'},
  {chapter:10,prompt:'Er ___ einen Kaffee ___.',options:['hat … bestellt','ist … bestellt','hat … bestellen'],answer:'hat … bestellt',explanation:'bestellen يأخذ haben، والتصريف الثالث bestellt.'},
  {chapter:10,prompt:'Ich ___ meine Freundin ___.',options:['habe … besucht','bin … besucht','habe … besuchen'],answer:'habe … besucht',explanation:'besuchen يأخذ haben، وPartizip II هو besucht.'},
  {chapter:10,prompt:'Sie ___ spät nach Hause ___.',options:['ist … gekommen','hat … gekommen','ist … kommen'],answer:'ist … gekommen',explanation:'kommen يأخذ sein في Perfekt.'},
  {chapter:11,prompt:'Das ist ___ Bruder.',options:['mein','meine','meinen'],answer:'mein',explanation:'Bruder مذكر في Nominativ: mein Bruder.'},
  {chapter:11,prompt:'Ich besuche ___ Mutter.',options:['meine','mein','meinen'],answer:'meine',explanation:'Mutter مؤنث في Akkusativ: meine Mutter.'},
  {chapter:11,prompt:'Ist das ___ Tasche?',options:['deine','dein','deinen'],answer:'deine',explanation:'Tasche مؤنث، لذلك نقول deine Tasche.'},
  {chapter:11,prompt:'Er sucht ___ Schlüssel.',options:['seinen','sein','seine'],answer:'seinen',explanation:'Schlüssel مذكر كمفعول Akkusativ: seinen Schlüssel.'},
  {chapter:11,prompt:'Wir wohnen bei ___ Eltern.',options:['unseren','unsere','unser'],answer:'unseren',explanation:'بعد bei يأتي Dativ؛ الجمع يأخذ unseren.'},
  {chapter:12,prompt:'Ich fahre ___ dem Bus.',options:['mit','für','ohne'],answer:'mit',explanation:'وسيلة النقل تأتي مع mit + Dativ.'},
  {chapter:12,prompt:'Das Geschenk ist ___ dich.',options:['für','mit','bei'],answer:'für',explanation:'für يأخذ Akkusativ، ومع الضمير du تصبح dich.'},
  {chapter:12,prompt:'Wir fahren ___ Berlin.',options:['nach','zu','bei'],answer:'nach',explanation:'نستخدم nach غالبًا مع أسماء المدن والبلدان من دون Artikel.'},
  {chapter:12,prompt:'Der Bus kommt ___ acht Uhr.',options:['um','am','im'],answer:'um',explanation:'نستخدم um مع الساعة المحددة.'},
  {chapter:12,prompt:'Ich bin ___ meiner Freundin.',options:['bei','für','durch'],answer:'bei',explanation:'bei تعني عند/لدى وتأخذ Dativ.'}
];
